version: '3.8'
services:
  postgresql:
    image: postgres:14.4
    environment:
      POSTGRES_DB: memewebsite
      POSTGRES_USER: meem
      POSTGRES_PASSWORD: meem
    volumes:
      - memewebsite:/var/lib/postgresql/data
  meme-backend:
    image: adamn2000/meme_website_backend:latest
    ports:
      - "8080:8080"
    environment:
      DB_HOST: "postgresql"
      DATABASE: "memewebsite"
      DB_PORT: 5432
      DBUSER: "meem"
      DBPASSWORD: "meem"
  meme-frontend:
    image: adamn2000/meme_website_frontend:latest
    ports:
      - "80:80"
volumes:
  memewebsite: