version: '3.8'
services:
  postgresql:
    image: postgres:14.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: memewebsite
      POSTGRES_USER: meem
      POSTGRES_PASSWORD: meem
    volumes:
      - memewebsite:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:6.10
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "meem.meem@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "meem"
volumes:
  memewebsite: