spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DATABASE:memewebsite}
    username: ${DB_USER:meem}
    password: ${DB_PASSWORD:meem}
  security:
    user:
      name: ${SECURITY_USER:meem}
      password: ${SECURITY_USER:meem}
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
server:
  servlet:
    context-path: /api
jwt:
  secretKeyAccessToken: superUberSecretAccessTokenKey123superUberSecretAccessTokenKey123superUberSecretAccessTokenKey123superUberSecretAccessTokenKey123
  secretKeyRefreshToken: superUberSecretRefreshTokenKey123superUberSecretRefreshTokenKey123superUberSecretRefreshTokenKey123superUberSecretRefreshTokenKey123
  tokenPrefix: "Bearer "
  claim: permissions
  accessTokenExpirationAfterDays: 10
  refreshTokenExpirationAfterDays: 30









