INSERT INTO COMMENT_STATISTIC(COMMENT_ID,ACCOUNT_ID,UP_VOTE,DOWN_VOTE)
VALUES
    (1,1,TRUE,FALSE),
    (2,2,FALSE,TRUE),
    (3,3,TRUE,FALSE),
    (4,4,TRUE,FALSE),
    (5,5,TRUE,FALSE),

    (6,1,TRUE,FALSE),
    (7,2,FALSE,TRUE),
    (8,3,TRUE,FALSE),
    (9,5,FALSE,TRUE),

    (3,1,TRUE,FALSE),
    (3,2,FALSE,TRUE),
    (3,3,TRUE,FALSE),
    (3,5,FALSE,TRUE);