INSERT INTO POST_STATISTIC(POST_ID,ACCOUNT_ID,SEEN,UP_VOTE,DOWN_VOTE,FAVORITE)
VALUES
(1,1,TRUE,TRUE,FALSE,FALSE),
(1,2,TRUE,FALSE,TRUE,FALSE),
(1,3,TRUE,TRUE,FALSE,FALSE),
(1,4,TRUE,FALSE,TRUE,TRUE),
(1,5,TRUE,TRUE,FALSE,FALSE),

(2,1,TRUE,FALSE,TRUE,FALSE),
(2,2,TRUE,FALSE,TRUE,TRUE),
(2,3,TRUE,FALSE,TRUE,FALSE),
(2,5,TRUE,FALSE,TRUE,FALSE),

(3,1,TRUE,TRUE,FALSE,TRUE),
(3,2,TRUE,TRUE,FALSE,FALSE),
(3,3,TRUE,TRUE,FALSE,FALSE),
(3,5,TRUE,TRUE,FALSE,FALSE);
